spring.datasource.url=jdbc:postgresql://dpg-d83tnf0jo89c73aam30g-a.singapore-postgres.render.com/moneymanager_of2n
spring.datasource.username=moneymanager_of2n_user
spring.datasource.password=1hUuy7S8FfbxVkq8Xm8xVO2tz2i4os4r
